### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by grawk** [krakenjs/construx-less#3]
Do you think we should pattern the major versions with the major versions of whatever is wrapped? If all modules used semver correctly that feels like the right thing to do.

But since some technologies break on minor, and some we haven't considered might not even have a major release yet... I'm not sure.

**Comment by grawk** [comment]
The other alternative imo would be to start all the plugins off at 1.0.0 regardless of the wrapped version

**Comment by aredridel** [comment]
1.0.0. There's other reasons it might break, the coupling is wishful at best.

**Comment by grawk** [comment]
Agreed. Thanks.
